defaults:
  - config
  - task: multivec
  - task/model: citadel_model

task:
  shared_model: false
  in_batch_eval: false
  optim:
    lr: 2e-5
  warmup_steps: 100
  add_cls: True
  model:
    model_path: allegro/herbert-base-cased

datamodule:
  train_path: /net/tscratch/people/plgdmytro/mgr/data/train_poleval_czywiesz.jsonl
  val_path: /net/tscratch/people/plgdmytro/mgr/data/dev_poleval_czywiesz.jsonl
  test_path: /net/tscratch/people/plgdmytro/mgr/data/dev_poleval_czywiesz.jsonl
  batch_size: 16
  num_negative: 1
  num_val_negative: 1
  num_test_negative: 50
  drop_last: false
  use_title: true

trainer:
  gpus: 1
  num_nodes: 1
  max_epochs: 40
  num_sanity_val_steps: 0
  log_every_n_steps: 10
  gradient_clip_val: 2.0
  precision: 16
  strategy: ddp_sharded
